version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: dataprove_mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - dataprove_mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: dataprove

volumes:
  dataprove_mongo_data:
